version: '3.8'

services:
  prism:
    build: .
    command: 'mock -h 0.0.0.0 /app/openapi.yaml'
    volumes:
      - ./specification/dist/openapi.yaml:/app/openapi.yaml
    ports:
      - '8080:4010'